### PR TITLE
Add DE slides

### PR DESCRIPTION
**Pull request by allyhawkins**
Last bit of #6 

I added in the PDF of the DE slides and added them to the schedule. Let me know if there are any comments that still need to be addressed before going in.

### CODE REVIEW

**Comment by sjspielman** [comment]
Macrophage/NK change looks good - those are super distinguishable, thanks!!
Slide 13 had PDF conversion fail (I think I remember this happening last time on this slide? Why, google drive, why?), so you need to scoot up the "Create `DESeqDataSet`" text inside the blue box up a smidge.

**Comment by jashapiro** [comment]
> Macrophage/NK change looks good - those are super distinguishable, thanks!! Slide 13 had PDF conversion fail (I think I remember this happening last time on this slide? Why, google drive, why?), so you need to scoot up the "Create `DESeqDataSet`" text inside the blue box up a smidge.

I agree! the real cell types help interpretability a lot. I made some minor formatting updates to standardize fonts, including making the text on slide 13 part of the boxes themselves, and that seemed to fix export.

**Comment by allyhawkins** [comment]
The PDF here has been updated to include the formatting changes.

**Review by jashapiro — APPROVED** [review]
LGTM!

**Pull request merged**
