### PR TITLE
Adding workshop intro slides

### LINKED ISSUE #17: Add workshop welcome and introduction slides
Update welcome and intro slides for the virtual advanced single-cell workshop. 

[**January slides**](https://github.com/AlexsLemonade/2023-january-training/blob/main/slides/2023-01-31_a_Workshop_Intro.pdf) for reference.

### PR DESCRIPTION
**Pull request by Jen-OMalley**
This closes #17.

### CODE REVIEW

**Comment by Jen-OMalley** [comment]
**@jashapiro** Do we want slide 21 (the cheatsheets) hidden? I think we hid that one for in-person.

**Comment by sjspielman** [comment]
@Jen-OMalley we actually have a new cheatsheet for scAdvanced, maybe we should do a screen shot of that _if_ we keep that slide! https://github.com/AlexsLemonade/training-modules/blob/master/module-cheatsheets/scRNA-seq-advanced-cheatsheet.pdf

**Comment by jashapiro** [comment]
We don't need to hide the cheatsheet slide; we will have those available this time 🎉 So we can keep it, but I am agnostic about which cheatsheet it actually shows.

Can you also add a link to these slides (the pdf) to the schedule?

**Comment by Jen-OMalley** [comment]
**@jashapiro** Okay I left the current cheatsheets screenshot and made the slide visible. Deepa also requested a downstream analysis eval slide, so I added one at the end. (She reviewed it.) 

Also added the PDF to the schedule.

**Review by jashapiro — COMMENTED** [review]
LGTM!

**Review by jashapiro — APPROVED** [review]

**Pull request merged**
